### ISSUE TITLE
Switch API checks to a command line option

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/quality-control#2]
I don't think there is need/desire to check the API results right now.  They appear to just want to validate that the new data is good/consistent.

Can you change the code so that the API checks only run if you type --api on the command line?

**Comment by Erin-Boehmer** [comment]
@joshuaellinger So all the data available for the API is reading from the sheets, right? So this could just be adding a line to `quality-control.ini` specifying whether the same code runs against the dev sheets or the api?
